#Friends
[friend_settings]
	#A list of users who can be chosen when it spawns a distant friend
	friends = ["MisterWiggly", "Arudaur", "Prof_Deadshot", "DDancer85"]
	#Add the players from the whitelist to the Friends list [default: true]
	addWhitelistPlayers = true

#Compat
[compat_settings]
	#Add players from a Player Mobs whitelist to the Friends list [default: false]
	playerMobsCompat = false
	#The player mobs Name Links, must start with https://whitelist.gorymoon.se
	playerMobsNameLinks = []
